name: Create and Upload Coverage Report

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests and generate coverage
      run: |
        swift test --enable-code-coverage
        xcrun llvm-cov export -format="lcov" .build/debug/YourPackageNameTests.xctest/Contents/MacOS/YourPackageNameTests > coverage.lcov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: coverage.lcov
