name: SwiftLint

on: [push, pull_request]

jobs:
  lint:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up SwiftLint
      run: |
        brew install swiftlint
    - name: Run SwiftLint
      run: swiftlint
